### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jinwk00** [logicplace/mabi-patch-thing#1]
INFO: Files/dirs affected in update: 38 to update, 14 to create
Traceback (most recent call last):
  File "download.py", line 501, in <module>
    try: sys.exit(main(sys.argv[1:]))
  File "download.py", line 479, in main
    patcher.continueDownloadFull(path, target)
  File "download.py", line 403, in continueDownloadFull
    self.downloadFiles(path, changes)
  File "download.py", line 253, in downloadFiles
    if data["objects"][0] == "__DIR__":
IndexError: list index out of range

**Comment by jinwk00** [comment]
Whenever I patch, this happens.

**Comment by logicplace** [comment]
Okay that should have fixed it, just not gonna test right now

**Comment by jinwk00** [comment]
Confirmed fixed.
